/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pucv.avancecurricular;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
//import java.awt.*;
/**
 *
 * @author alfar
 */
public class AvanceCurricularSwing extends javax.swing.JFrame {

    /**
     * Creates new form AvanceCurricularSwing
     */
    DatosPersonal datos = new DatosPersonal();
    public AvanceCurricularSwing() {
        initComponents();
        initComponentss();
    }
   
    
    private void initComponentss() {
        JLabel labelConImagen = new JLabel(new ImageIcon("C:\\Users\\alfar\\Desktop\\proyecto avanzada\\FGintKnXEAERKKN.jpg"));
        labelConImagen.setBounds(0, 0, jDesktopPane1.getWidth(), jDesktopPane1.getHeight());
        jDesktopPane1.add(labelConImagen);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        csvVisor = new javax.swing.JPanel();
        PanelButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenuButton = new javax.swing.JMenu();
        csvMenuItemExportar = new javax.swing.JMenuItem();
        csvMenuItemCargar = new javax.swing.JMenuItem();
        mallaMenuButton = new javax.swing.JMenu();
        mallaMenuItemVerMalla = new javax.swing.JMenuItem();
        mallaMenuItemAgregarMalla = new javax.swing.JMenuItem();
        mallaMenuItemAgragarAsig = new javax.swing.JMenuItem();
        mallaMenuItemQuitarMalla = new javax.swing.JMenuItem();
        alumnosMenuButton = new javax.swing.JMenu();
        alumnoMenuItemAgregarAlumno = new javax.swing.JMenuItem();
        alumnoMenuItemAvance = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avance Curricular (GUI)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        csvVisor.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout csvVisorLayout = new javax.swing.GroupLayout(csvVisor);
        csvVisor.setLayout(csvVisorLayout);
        csvVisorLayout.setHorizontalGroup(
            csvVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        csvVisorLayout.setVerticalGroup(
            csvVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        PanelButtons.setBackground(new java.awt.Color(0, 255, 0));
        PanelButtons.setForeground(new java.awt.Color(51, 51, 51));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        javax.swing.GroupLayout PanelButtonsLayout = new javax.swing.GroupLayout(PanelButtons);
        PanelButtons.setLayout(PanelButtonsLayout);
        PanelButtonsLayout.setHorizontalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelButtonsLayout.setVerticalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(csvVisor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PanelButtons, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(csvVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(csvVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        archivoMenuButton.setText("Archivo");

        csvMenuItemExportar.setText("Exportar csv");
        csvMenuItemExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvMenuItemExportarActionPerformed(evt);
            }
        });
        archivoMenuButton.add(csvMenuItemExportar);

        csvMenuItemCargar.setText("Cargar csv");
        csvMenuItemCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvMenuItemCargarActionPerformed(evt);
            }
        });
        archivoMenuButton.add(csvMenuItemCargar);

        jMenuBar1.add(archivoMenuButton);

        mallaMenuButton.setText("Mallas");

        mallaMenuItemVerMalla.setText("Ver mallas");
        mallaMenuItemVerMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallaMenuItemVerMallaActionPerformed(evt);
            }
        });
        mallaMenuButton.add(mallaMenuItemVerMalla);

        mallaMenuItemAgregarMalla.setText("Agregar malla");
        mallaMenuItemAgregarMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallaMenuItemAgregarMallaActionPerformed(evt);
            }
        });
        mallaMenuButton.add(mallaMenuItemAgregarMalla);

        mallaMenuItemAgragarAsig.setText("Agregar Asignaturas a malla");
        mallaMenuItemAgragarAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallaMenuItemAgragarAsigActionPerformed(evt);
            }
        });
        mallaMenuButton.add(mallaMenuItemAgragarAsig);

        mallaMenuItemQuitarMalla.setText("Quitar malla");
        mallaMenuItemQuitarMalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallaMenuItemQuitarMallaActionPerformed(evt);
            }
        });
        mallaMenuButton.add(mallaMenuItemQuitarMalla);

        jMenuBar1.add(mallaMenuButton);

        alumnosMenuButton.setText("Alumnos");

        alumnoMenuItemAgregarAlumno.setText("Agregar alumno");
        alumnosMenuButton.add(alumnoMenuItemAgregarAlumno);

        alumnoMenuItemAvance.setText("Administrar avance ");
        alumnoMenuItemAvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoMenuItemAvanceActionPerformed(evt);
            }
        });
        alumnosMenuButton.add(alumnoMenuItemAvance);

        jMenuBar1.add(alumnosMenuButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mallaMenuItemAgregarMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallaMenuItemAgregarMallaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mallaMenuItemAgregarMallaActionPerformed

    private void mallaMenuItemQuitarMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallaMenuItemQuitarMallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mallaMenuItemQuitarMallaActionPerformed

    private void mallaMenuItemVerMallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallaMenuItemVerMallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mallaMenuItemVerMallaActionPerformed

    private void alumnoMenuItemAvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoMenuItemAvanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alumnoMenuItemAvanceActionPerformed
    
    private void csvMenuItemExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvMenuItemExportarActionPerformed

        
    }//GEN-LAST:event_csvMenuItemExportarActionPerformed

    private void csvMenuItemCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvMenuItemCargarActionPerformed
      
    }//GEN-LAST:event_csvMenuItemCargarActionPerformed

    private void mallaMenuItemAgragarAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallaMenuItemAgragarAsigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mallaMenuItemAgragarAsigActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvanceCurricularSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvanceCurricularSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvanceCurricularSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvanceCurricularSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvanceCurricularSwing().setVisible(true);
            }
        });
    }
    
    public JMenuItem GetCsvCargarButton() {
        return csvMenuItemCargar;
    }
    
    public JMenuItem GetCsvExpotarButton() {
        return csvMenuItemExportar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JMenuItem alumnoMenuItemAgregarAlumno;
    private javax.swing.JMenuItem alumnoMenuItemAvance;
    private javax.swing.JMenu alumnosMenuButton;
    private javax.swing.JMenu archivoMenuButton;
    private javax.swing.JMenuItem csvMenuItemCargar;
    private javax.swing.JMenuItem csvMenuItemExportar;
    private javax.swing.JPanel csvVisor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel label;
    private javax.swing.JMenu mallaMenuButton;
    private javax.swing.JMenuItem mallaMenuItemAgragarAsig;
    private javax.swing.JMenuItem mallaMenuItemAgregarMalla;
    private javax.swing.JMenuItem mallaMenuItemQuitarMalla;
    private javax.swing.JMenuItem mallaMenuItemVerMalla;
    // End of variables declaration//GEN-END:variables
}
